import { Inter } from "next/font/google";
import StyledComponentsRegistry from "./library/registry";
import GlobalStyles from "./GlobalStyles";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <GlobalStyles/>
            {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
